// aprendiendovue/src/components/Cancion.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="cancion.image" :alt="cancion.title" />
    </div>

    <h2>{{ cancion.title }}</h2>

    <a href="article.html">Leer más</a>

    <input
      type="button"
      value="Marcar como favorita"
      @click="pasarFavoritaAlPadre(cancion)"
    />

    <span
      class="date"
      v-bind:class="{
        yeargreen: cancion.year >= 2015,
        yearred: cancion.year < 2015,
      }"
    >
      {{ cancion.year }}
    </span>

    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "Cancion",
  props: ["cancion"],
  mounted() {},
  methods: {
    pasarFavoritaAlPadre(cancion) {
      this.$emit("favorita", cancion);
    },
  },
};
</script>

// AprendiendoAngular/src/app/components/cancion/cancion.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Musica } from '../../models/musica'

@Component({
  selector: 'app-cancion',
  templateUrl: './cancion.component.html',
  styleUrls: ['./cancion.component.css']
})
export class CancionComponent implements OnInit {

  @Input() cancion: Musica;
  @Output() marcarFavorita = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event, cancion) {
    this.marcarFavorita.emit({
      cancion: cancion
    })
  }

}

<article class="article-item">

    <div class="image-wrap">
        <img src="{{cancion.image}}" alt="cancion.title">
    </div>

    <h2>{{cancion.test}} - {{cancion.title}}</h2>
    <span class="date">
        Hace 5 minutos
    </span>

    <a href="article.html">Leer más</a>


    <!-- 
        [class.year-green]="pelicula.year > 2016" 
        [class.year-red]="pelicula.year <= 2016" -->
    <span class="year" [ngClass]="{
            'year-green': cancion.year > 2016,
            'year-red': cancion.year <= 2016
        }">
        {{cancion.year}}
    </span>

    <button class="btn btn-success" style="font-size: 12px; margin-top: 15px;" (click)="seleccionar($event, cancion)">
        Seleccionar como favorita
    </button>


    <div class="clearfix"></div>
</article>
