// aprendiendovue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Cosas que puedes realizar</h3>
      <a href="#" class="btn btn-success">Crear articulo</a>
    </div>
    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el articulo que buscas</p>
      <form action="">
        <input type="text" name="search" />
        <input type="submit" name="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar",
};
</script>

// AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router'

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public searchString: string;

  constructor(
    private _router: Router,
    private _route: ActivatedRoute
  ) { }

  ngOnInit(): void {
  }

  goSearch() {
    this._router.navigate(['/buscar', this.searchString])
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Cosas que puedes realizar</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear articulo</a>
    </div>
    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el articulo que buscas</p>
        <form #searchForm = "ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" [(ngModel)]="searchString">
            <input type="submit" name="submit" value="Buscar" class="btn">
        </form>
    </div>
</aside>

<div class="clearfix"></div>
