// AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo: string;

  constructor() {
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    };
  }

  ngOnInit(): void {
  }

  onSubmit() {
    alert('Formulario enviado');
    console.log(this.user);
  }

  hasDadoClick() {
    alert('has dado clic')
  }

  hasSalido() {
    alert('has salido!')
  }

}

<app-slider [nombre]="'Formulario.'" [size]="'small'"></app-slider>

<div class="center">

  <section id="content">

    <h1 class="subheader">Formulario</h1>

    <!--
    <div id="datos-al-vuelo" *ngIf="user.nombre">
      <h2 class="subheader">Datos al vuelo</h2>
      <ul class="center">
        <li>{{user.nombre}}</li>
        <li>{{user.apellidos}}</li>
        <li>{{user.bio}}</li>
        <li>{{user.genero}}</li>
      </ul>
    </div>
    -->

    <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">

      <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" required pattern="[a-zA-Z]+">
        <small *ngIf="!nombre.valid && nombre.touched">
          El nombre no es valido
        </small>
      </div>

      <div class="form-group">
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required>
        <small *ngIf="!apellidos.valid && apellidos.touched">
          Apellidos no validos
        </small>
      </div>

      <div class="form-group">
        <label for="bio">Biografia</label>
        <textarea name="bio" cols="30" rows="10" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
        <small *ngIf="!bio.valid && bio.touched">
          Biografia no valida
        </small>
      </div>

      <div class="form-group radiobuttons">
        <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.genero" required/> Mujer
        <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)]="user.genero"/> Hombre
        <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)]="user.genero"/> Otro
        <small *ngIf="!genero.valid && genero.touched">
          Apellidos no validos
        </small>
      </div>

      <div class="clearfix"></div>

      <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid">

    </form>

    <h2 class="subheader">Eventos</h2>
    <button (click)="hasDadoClick()">Click!</button>
    <input type="text" [(ngModel)]="campo" (blur)="hasSalido()">
    {{campo}}

  </section>

  <app-sidebar></app-sidebar>
</div>

// aprendiendovue/src/components/Formulario.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <h2 class="subheader">Formulario</h2>

        <form class="mid-form" @submit.prevent="mostrarUsuario()">
          <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" v-model="user.nombre" />
          </div>
          <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" name="apellidos" v-model="user.apellidos" />
          </div>
          <div class="form-group">
            <label for="bio">Biografia</label>
            <textarea name="bio" v-model="user.bio"></textarea>
          </div>
          <div class="form-group radiobuttons">
            <input
              type="radio"
              name="genero"
              value="hombre"
              v-model="user.genero"
            />
            Hombre
            <input
              type="radio"
              name="genero"
              value="mujer"
              v-model="user.genero"
            />
            Mujer
            <input
              type="radio"
              name="genero"
              value="otro"
              v-model="user.genero"
            />
            Otro
          </div>
          <div class="clearfix"></div>
          <input type="submit" value="Enviar" class="btn btn-success" />
        </form>

        <div class="datos" v-if="user">
          <h3>{{user.nombre + ' ' + user.apellidos}}</h3>
        </div>

      </section>

      <Sidebar />
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import { required, minLenght } from "vuelidate/lib/validators";
import Sidebar from "./Sidebar.vue";

export default {
  name: "Formulario",
  components: {
    Sidebar,
  },
  validations: {
    nombre: {
      required,
      minLenght: minLenght(2)
    },
    apellidos: {
      required,
      minLenght: minLenght(2)
    },
    bio: {
      required,
      minLenght: minLenght(10)
    }
  },
  data() {
    return {
      user: {
        nombre: "",
        apellidos: "",
        bio: "",
        genero: "",
      },
    };
  },
  methods: {
    mostrarUsuario() {
      console.log(this.user);
    },
  },
};
</script>
